"use client";
import { useEffect, useState } from "react";
import { ChevronLeft, ChevronRight } from "lucide-react";
import DriveImage from "../shared/DriveImage";

export default function LivePreview({ product, fields, settings = {} }) {
  const [selectedVariant, setSelectedVariant] = useState(0);
  const [imageIndex, setImageIndex] = useState(0);
  useEffect(() => { if (selectedVariant >= (product.variants?.length || 0)) setSelectedVariant(0); setImageIndex(0); }, [product.variants, selectedVariant]);
  const variant = product.has_variants ? product.variants?.[selectedVariant] : null;
  const price = variant?.price ?? product.selling_price ?? product.base_price;
  const images = [...new Set([variant?.image_url, ...(product.images || [])].filter(Boolean))];
  return <div className="mx-auto w-[300px]"><div className="rounded-[2rem] border-[6px] border-[var(--ink)] bg-[var(--ink)] shadow-xl"><div className="flex h-5 items-center justify-center"><div className="h-1 w-10 rounded-full bg-[var(--paper)]/30" /></div><div className="h-[560px] overflow-y-auto rounded-b-[1.6rem] bg-[var(--paper)]"><div className="sticky top-0 z-10 border-b border-dashed border-[var(--line)] bg-[var(--paper)]/95 px-4 py-2 backdrop-blur"><p className="text-[10px] tracking-widest text-[var(--muted)]">PRATINJAU ETALASE</p></div><div className="relative aspect-square w-full bg-[var(--canvas)]">{images.length ? <DriveImage src={images[imageIndex % images.length]} alt={product.name} className="size-full object-cover" /> : <div className="flex size-full items-center justify-center text-xs text-[var(--muted)]">Belum ada gambar</div>}{images.length > 1 && <><button type="button" onClick={() => setImageIndex((imageIndex - 1 + images.length) % images.length)} className="absolute left-2 top-1/2 rounded-full bg-[var(--paper)]/80 p-1" aria-label="Gambar sebelumnya"><ChevronLeft data-icon="inline-start" /></button><button type="button" onClick={() => setImageIndex((imageIndex + 1) % images.length)} className="absolute right-2 top-1/2 rounded-full bg-[var(--paper)]/80 p-1" aria-label="Gambar berikutnya"><ChevronRight data-icon="inline-start" /></button></>}</div><div className="flex flex-col gap-4 p-4"><div><h3 className="font-display text-base font-semibold text-[var(--ink)]">{product.name || "Nama produk"}</h3><p className="mt-1 text-xs text-[var(--muted)]">{product.description || "Deskripsi produk akan tampil di sini."}</p></div><p className="font-mono text-lg font-semibold text-[var(--ink)]">Rp{Number(price || 0).toLocaleString("id-ID")}</p>{product.has_variants && product.variants?.length > 0 && <div className="flex flex-wrap gap-2"><p className="w-full text-xs font-medium text-[var(--muted)]">Pilih varian</p>{product.variants.map((v, i) => <button key={v.sku || i} type="button" onClick={() => setSelectedVariant(i)} className={`rounded-full border px-3 py-1 text-xs font-medium ${i === selectedVariant ? "border-[var(--ink)] bg-[var(--ink)] text-[var(--paper)]" : "border-[var(--line)]"}`}>{v.name}</button>)}</div>}{fields?.length > 0 && <div className="flex flex-col gap-3 border-t border-dashed border-[var(--line)] pt-3">{fields.map((field) => <PreviewField key={field.field_id} field={field} />)}</div>}<button type="button" disabled className="w-full rounded-md bg-[var(--marigold)]/50 py-2.5 text-sm font-semibold text-[var(--ink)]/60">Bayar Sekarang</button></div></div></div></div>;
}
function PreviewField({ field }) { const base = "w-full rounded-md border border-[var(--line)] bg-[var(--paper)] px-2.5 py-1.5 text-xs"; return <div className="flex flex-col gap-1"><label className="text-xs font-medium text-[var(--ink)]">{field.label || "(label kosong)"}{field.is_required && <span className="text-[var(--brick)]"> *</span>}</label>{field.type === "textarea" ? <textarea disabled rows={2} className={base} placeholder="Isian panjang" /> : field.type === "dropdown" ? <select disabled className={base}><option>Pilih salah satu</option>{field.options?.map((o, i) => <option key={i}>{o}</option>)}</select> : <input disabled type={field.type === "number" ? "number" : "text"} className={base} placeholder="Isian singkat" />}</div>; }
